### PR TITLE
Update PluginSdkVsTools.vsix

### PR DESCRIPTION
**Pull request by FrannDzs**
Fixed extension manifest to allow installation in Visual Studio 2022.

### CODE REVIEW

**Comment by TheArtemMaps** [comment]
i agree, accept this, so people will have support for vs2022

**Comment by FrannDzs** [comment]
> 



> i agree, accept this, so people will have support for vs2022

Not fixed, changing the manifest will install the extension, but it does not work.

**Comment by TheArtemMaps** [comment]
> > 
> 
> > i agree, accept this, so people will have support for vs2022
> 
> Not fixed, changing the manifest will install the extension, but it does not work.

yep, i know. too bad...

**Comment by FrannDzs** [comment]
Useful links:

- https://learn.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022

- https://cezarypiatek.github.io/post/migrate-vsix-to-vs2022/

- https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Pull request closed without merging**
