### PR TITLE
Fix typo for debug command

### PR DESCRIPTION
**Pull request by N4T4NM**
The executable is called "gta_sa.exe". I can't confirm if this is the case on all versions of the game, but I don't remember the seeing a different name for the executable.

### CODE REVIEW

**Comment by ViperJohnGR** [comment]
"gta-sa.exe" is the Steam version.

**Comment by TheArtemMaps** [comment]
Need to implement some sort of steam exe name check.

**Comment by TheArtemMaps** [comment]
And this actually fixed the "System couldn't find file" error

**Comment by N4T4NM** [comment]
@TheArtemMaps I updated the script, may not look very clean but it seems to work.

**Pull request merged**
